version: "3"

services:
  web:
    build: .
    depends_on:
      - mongodb
    links:
      - mongodb
    ports:
      - "8080:8080"

  mongodb:
    image: mongo:5.0
    ports:
      - 27017:27017
    volumes:
      - ~/apps/mongo:/data/db

volumes:
  data: